# This file created by conda-build 2.1.18
# meta.yaml template originally from:
# C:\projects\opencv-feedstock\recipe, last modified Sun Mar 11 01:42:36 2018
# ------------------------------------------------

package:
    name: opencv
    version: 3.4.1
source:
    fn: opencv-3.4.1.tar.gz
    sha256: f1b87684d75496a1054405ae3ee0b6573acaf3dad39eaf4f1d66fdd7e03dc852
    url: https://github.com/opencv/opencv/archive/3.4.1.tar.gz
build:
    noarch: ''
    noarch_python: false
    number: '200'
    string: py36_200
requirements:
    build:
        - ca-certificates 2018.1.18 0
        - cmake 3.10.0 4
        - curl 7.55.1 vc14_0
        - eigen 3.2.8 2
        - git 2.14.2 3
        - icc_rt 2017.0.4 h97af966_0
        - icu 58.2 vc14_0
        - intel-openmp 2018.0.0 hd92c6cd_8
        - jpeg 9b vc14_2
        - krb5 1.14.2 vc14_0
        - libpng 1.6.34 vc14_0
        - libssh2 1.8.0 vc14_2
        - libtiff 4.0.9 vc14_0
        - libwebp 0.5.2 vc14_7
        - mkl 2018.0.1 h2108138_4
        - numpy 1.11.3 py36h4a99626_4
        - openssl 1.0.2n vc14_0
        - python 3.6.4 0
        - qt 5.6.2 vc14_2
        - sqlite 3.13.0 vc14_0
        - toolchain 2.1.2 0
        - vc 14 0
        - vs2015_runtime 14.0.25420 0
        - zlib 1.2.11 vc14_0
    run:
        - python
        - numpy >=1.11
        - zlib 1.2.11
        - jpeg 9*
        - libwebp 0.5.*
        - libtiff >=4.0.8,<4.0.10
        - libpng >=1.6.32,<1.6.35
        - qt 5.6.*
test:
    commands:
        - if not exist %PREFIX%\\Library\\bin\\opencv_aruco341.dll exit 1
        - if not exist %PREFIX%\\Library\\bin\\opencv_bgsegm341.dll exit 1
        - if not exist %PREFIX%\\Library\\bin\\opencv_calib3d341.dll exit 1
        - if not exist %PREFIX%\\Library\\bin\\opencv_ccalib341.dll exit 1
        - if not exist %PREFIX%\\Library\\bin\\opencv_core341.dll exit 1
        - if not exist %PREFIX%\\Library\\bin\\opencv_datasets341.dll exit 1
        - if not exist %PREFIX%\\Library\\bin\\opencv_dnn341.dll exit 1
        - if not exist %PREFIX%\\Library\\bin\\opencv_dpm341.dll exit 1
        - if not exist %PREFIX%\\Library\\bin\\opencv_face341.dll exit 1
        - if not exist %PREFIX%\\Library\\bin\\opencv_features2d341.dll exit 1
        - if not exist %PREFIX%\\Library\\bin\\opencv_flann341.dll exit 1
        - if not exist %PREFIX%\\Library\\bin\\opencv_fuzzy341.dll exit 1
        - if not exist %PREFIX%\\Library\\bin\\opencv_highgui341.dll exit 1
        - if not exist %PREFIX%\\Library\\bin\\opencv_imgcodecs341.dll exit 1
        - if not exist %PREFIX%\\Library\\bin\\opencv_imgproc341.dll exit 1
        - if not exist %PREFIX%\\Library\\bin\\opencv_line_descriptor341.dll exit
            1
        - if not exist %PREFIX%\\Library\\bin\\opencv_ml341.dll exit 1
        - if not exist %PREFIX%\\Library\\bin\\opencv_objdetect341.dll exit 1
        - if not exist %PREFIX%\\Library\\bin\\opencv_optflow341.dll exit 1
        - if not exist %PREFIX%\\Library\\bin\\opencv_phase_unwrapping341.dll exit
            1
        - if not exist %PREFIX%\\Library\\bin\\opencv_photo341.dll exit 1
        - if not exist %PREFIX%\\Library\\bin\\opencv_plot341.dll exit 1
        - if not exist %PREFIX%\\Library\\bin\\opencv_reg341.dll exit 1
        - if not exist %PREFIX%\\Library\\bin\\opencv_rgbd341.dll exit 1
        - if not exist %PREFIX%\\Library\\bin\\opencv_saliency341.dll exit 1
        - if not exist %PREFIX%\\Library\\bin\\opencv_shape341.dll exit 1
        - if not exist %PREFIX%\\Library\\bin\\opencv_stereo341.dll exit 1
        - if not exist %PREFIX%\\Library\\bin\\opencv_stitching341.dll exit 1
        - if not exist %PREFIX%\\Library\\bin\\opencv_structured_light341.dll exit
            1
        - if not exist %PREFIX%\\Library\\bin\\opencv_superres341.dll exit 1
        - if not exist %PREFIX%\\Library\\bin\\opencv_surface_matching341.dll exit
            1
        - if not exist %PREFIX%\\Library\\bin\\opencv_text341.dll exit 1
        - if not exist %PREFIX%\\Library\\bin\\opencv_tracking341.dll exit 1
        - if not exist %PREFIX%\\Library\\bin\\opencv_video341.dll exit 1
        - if not exist %PREFIX%\\Library\\bin\\opencv_videoio341.dll exit 1
        - if not exist %PREFIX%\\Library\\bin\\opencv_videostab341.dll exit 1
        - if not exist %PREFIX%\\Library\\bin\\opencv_xfeatures2d341.dll exit 1
        - if not exist %PREFIX%\\Library\\bin\\opencv_ximgproc341.dll exit 1
        - if not exist %PREFIX%\\Library\\bin\\opencv_xobjdetect341.dll exit 1
        - if not exist %PREFIX%\\Library\\bin\\opencv_xphoto341.dll exit 1
    imports:
        - cv2
        - cv2.xfeatures2d
    requires:
        - requests
        - certifi
about:
    home: http://opencv.org/
    license: BSD 3-clause
    summary: Computer vision and machine learning software library.
extra:
    final: true
    recipe-maintainers:
        - jakirkham
        - msarahan
        - patricksnape
        - zym1010
        - hajapy
        - ocefpaf
