# This file created by conda-build 2.1.17
# meta.yaml template originally from:
# C:\projects\dlib-feedstock\recipe, last modified Thu Aug 31 15:35:34 2017
# ------------------------------------------------

package:
    name: dlib
    version: '19.4'
source:
    patches:
        - win_boost.patch
        - win_png.patch
        - win_jpeg.patch
        - win_release_flags.patch
    sha256: 2bed9669f1a5c436579498d0806b27a9b60c42a975a9b6e67b594b40f58b1a88
    url: https://github.com/davisking/dlib/archive/v19.4.tar.gz
build:
    noarch: ''
    noarch_python: false
    number: '201'
    string: np113py35_201
requirements:
    build:
        - python 3.5.4 0
        - boost-cpp 1.64.0 vc14_1
        - vc 14 0
        - libpng 1.6.28 vc14_1
        - vs2015_runtime 14.0.25420 0
        - vs2013_runtime 12.0.21005 1
        - mkl 2017.0.3 0
        - boost 1.64.0 py35_vc14_4
        - numpy 1.13.1 py35_0
        - cmake 3.9.1 0
        - zlib 1.2.8 vc14_3
        - toolchain 2.0.0 0
    run:
        - python
        - numpy x.x
        - boost 1.64.*
        - libpng >=1.6.28,<1.7
test:
    files:
        - test_data/face.jpg
        - test_data/face.png
        - test_data/images.xml
    imports:
        - dlib
    requires:
        - tqdm
        - pillow
about:
    home: http://dlib.net/
    license: Boost 1.0
    license_file: dlib/LICENSE.txt
    summary: Modern C++ toolkit containing machine learning algorithms with Python
        bindings
extra:
    final: true
    recipe-maintainers:
        - patricksnape
